# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.runs/synth_1/.Xil/Vivado-21692-DESKTOP-AKM0555/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter areaStrategy 3
    set rt::partid xc7z020clg400-2
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/70cf/hdl
    c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/58e2/hdl
    c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/ec67/hdl
    c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/979d/hdl/verilog
    c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/b2d0/hdl/verilog
  } {
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/979d/hdl/sc_util_v1_0_vl_rfs.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_2/synth/bd_267f_arsw_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_3/synth/bd_267f_rsw_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_4/synth/bd_267f_awsw_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_5/synth/bd_267f_wsw_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_6/synth/bd_267f_bsw_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/f85e/hdl/sc_mmu_v1_0_vl_rfs.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_7/synth/bd_267f_s00mmu_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/ca72/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_8/synth/bd_267f_s00tr_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/9ade/hdl/sc_si_converter_v1_0_vl_rfs.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_9/synth/bd_267f_s00sic_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/b89e/hdl/sc_axi2sc_v1_0_vl_rfs.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_10/synth/bd_267f_s00a2s_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/b2d0/hdl/sc_node_v1_0_vl_rfs.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_11/synth/bd_267f_sarn_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_12/synth/bd_267f_srn_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_13/synth/bd_267f_sawn_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_14/synth/bd_267f_swn_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_15/synth/bd_267f_sbn_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_16/synth/bd_267f_s01mmu_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_17/synth/bd_267f_s01tr_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_18/synth/bd_267f_s01sic_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_19/synth/bd_267f_s01a2s_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_20/synth/bd_267f_sarn_1.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_21/synth/bd_267f_srn_1.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/7005/hdl/sc_sc2axi_v1_0_vl_rfs.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_22/synth/bd_267f_m00s2a_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_23/synth/bd_267f_m00arn_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_24/synth/bd_267f_m00rn_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_25/synth/bd_267f_m00awn_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_26/synth/bd_267f_m00wn_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_27/synth/bd_267f_m00bn_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/b387/hdl/sc_exit_v1_0_vl_rfs.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_28/synth/bd_267f_m00e_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_29/synth/bd_267f_m01s2a_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_30/synth/bd_267f_m01arn_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_31/synth/bd_267f_m01rn_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_32/synth/bd_267f_m01awn_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_33/synth/bd_267f_m01wn_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_34/synth/bd_267f_m01bn_0.sv
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_35/synth/bd_267f_m01e_0.sv
      D:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      D:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      D:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/70cf/hdl
    c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/58e2/hdl
    c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/ec67/hdl
    c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/979d/hdl/verilog
    c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/b2d0/hdl/verilog
  } {
      C:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/imports/pl/interpolation/average_adjust_16point.v
      C:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/imports/pl/interpolation/edge_16_generate.v
      C:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/imports/pl/interpolation/gauss_filter.v
      C:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/imports/pl/interpolation/gauss_filter_dot_36_4k.v
      C:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/imports/pl/interpolation/interpolate_16point.v
      C:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/imports/pl/interpolation/single_color_top.v
      C:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/imports/pl/interpolation/top.v
      C:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/imports/pl/key_debounce.v
      C:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/hdl/sys_bd_design_wrapper.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_aw_atc.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_b_atc.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_w_atc.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_atc.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_trace_buffer.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_processing_system7_0_0/hdl/verilog/processing_system7_v5_5_processing_system7.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_processing_system7_0_0/synth/sys_bd_design_processing_system7_0_0.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_top_0_0/synth/sys_bd_design_top_0_0.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_key_debounce_0_0/synth/sys_bd_design_key_debounce_0_0.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_util_vector_logic_0_0/synth/sys_bd_design_util_vector_logic_0_0.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/6bb8/hdl/axi_ddr_rw_v1_0_M_AXI.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/6bb8/hdl/axi_ddr_rw_v1_0.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_axi_ddr_rw_0_0/synth/sys_bd_design_axi_ddr_rw_0_0.v
      C:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/synth/sys_bd_design.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/58e2/hdl/axi_vdma_v6_3_rfs.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/a87e/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_v_axi4s_vid_out_0_1/synth/sys_bd_design_v_axi4s_vid_out_0_1.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/ab26/src/mmcme2_drp.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/cc23/hdl/axi_register_slice_v2_1_vl_rfs.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/c4fd/hdl/axi_data_fifo_v2_1_vl_rfs.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/6c9d/hdl/axi_crossbar_v2_1_vl_rfs.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_xbar_2/synth/sys_bd_design_xbar_2.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/31a1/src/asyn_rst_syn.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/31a1/src/dvi_encoder.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/31a1/src/serializer_10_to_1.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/31a1/src/dvi_transmitter_top.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_DVI_Transmitter_0_0/synth/sys_bd_design_DVI_Transmitter_0_0.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/synth/sys_bd_design_smartconnect_0_0.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/synth/bd_267f.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/4649/hdl/xlconstant_v1_1_vl_rfs.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_0/synth/bd_267f_one_0.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/7a04/hdl/axi_protocol_converter_v2_1_vl_rfs.v
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_auto_pc_0/synth/sys_bd_design_auto_pc_0.v
    }
      rt::read_vhdl -lib lib_cdc_v1_0_2 c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_13 c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_rst_ps7_0_50M_0/synth/sys_bd_design_rst_ps7_0_50M_0.vhd
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_axi_vdma_0_1/synth/sys_bd_design_axi_vdma_0_1.vhd
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_v_tc_0_1/synth/sys_bd_design_v_tc_0_1.vhd
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/ab26/src/axi_dynclk_S00_AXI.vhd
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/ab26/src/axi_dynclk.vhd
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_axi_dynclk_0_1/synth/sys_bd_design_axi_dynclk_0_1.vhd
      c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_1/synth/bd_267f_psr_aclk_0.vhd
    }
      rt::read_vhdl -lib lib_pkg_v1_0_2 c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_fifo_v1_0_12 c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/544a/hdl/lib_fifo_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_bmg_v1_0_11 c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/556c/hdl/lib_bmg_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_srl_fifo_v1_0_2 c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd
      rt::read_vhdl -lib axi_datamover_v5_1_20 c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/dfb3/hdl/axi_datamover_v5_1_vh_rfs.vhd
      rt::read_vhdl -lib axi_vdma_v6_3_6 c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/58e2/hdl/axi_vdma_v6_3_rfs.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_4_2 c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/37c2/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_2_3 c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/64f4/hdl/fifo_generator_v13_2_vhsyn_rfs.vhd
      rt::read_vhdl -lib axi_lite_ipif_v3_0_4 c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib v_tc_v6_1_13 c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ipshared/a92c/hdl/v_tc_v6_1_vh_rfs.vhd
      rt::read_vhdl -lib xpm D:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top sys_bd_design_wrapper
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.runs/synth_1/.Xil/Vivado-21692-DESKTOP-AKM0555/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
