# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pl_constraints.xdc

# Block Designs: bd/sys_bd_design/sys_bd_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_design || ORIG_REF_NAME==sys_bd_design} -quiet] -quiet

# IP: bd/sys_bd_design/ip/sys_bd_design_processing_system7_0_0/sys_bd_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_design_processing_system7_0_0 || ORIG_REF_NAME==sys_bd_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/sys_bd_design/ip/sys_bd_design_top_0_0/sys_bd_design_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_design_top_0_0 || ORIG_REF_NAME==sys_bd_design_top_0_0} -quiet] -quiet

# IP: bd/sys_bd_design/ip/sys_bd_design_key_debounce_0_0/sys_bd_design_key_debounce_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_design_key_debounce_0_0 || ORIG_REF_NAME==sys_bd_design_key_debounce_0_0} -quiet] -quiet

# IP: bd/sys_bd_design/ip/sys_bd_design_util_vector_logic_0_0/sys_bd_design_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_design_util_vector_logic_0_0 || ORIG_REF_NAME==sys_bd_design_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/sys_bd_design/ip/sys_bd_design_axi_ddr_rw_0_0/sys_bd_design_axi_ddr_rw_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_design_axi_ddr_rw_0_0 || ORIG_REF_NAME==sys_bd_design_axi_ddr_rw_0_0} -quiet] -quiet

# IP: bd/sys_bd_design/ip/sys_bd_design_rst_ps7_0_50M_0/sys_bd_design_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==sys_bd_design_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/sys_bd_design/ip/sys_bd_design_axi_vdma_0_1/sys_bd_design_axi_vdma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_design_axi_vdma_0_1 || ORIG_REF_NAME==sys_bd_design_axi_vdma_0_1} -quiet] -quiet

# IP: bd/sys_bd_design/ip/sys_bd_design_v_tc_0_1/sys_bd_design_v_tc_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_design_v_tc_0_1 || ORIG_REF_NAME==sys_bd_design_v_tc_0_1} -quiet] -quiet

# IP: bd/sys_bd_design/ip/sys_bd_design_v_axi4s_vid_out_0_1/sys_bd_design_v_axi4s_vid_out_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_design_v_axi4s_vid_out_0_1 || ORIG_REF_NAME==sys_bd_design_v_axi4s_vid_out_0_1} -quiet] -quiet

# IP: bd/sys_bd_design/ip/sys_bd_design_axi_dynclk_0_1/sys_bd_design_axi_dynclk_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_design_axi_dynclk_0_1 || ORIG_REF_NAME==sys_bd_design_axi_dynclk_0_1} -quiet] -quiet

# IP: bd/sys_bd_design/ip/sys_bd_design_xbar_2/sys_bd_design_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_design_xbar_2 || ORIG_REF_NAME==sys_bd_design_xbar_2} -quiet] -quiet

# IP: bd/sys_bd_design/ip/sys_bd_design_ps7_0_axi_periph_1/sys_bd_design_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_design_ps7_0_axi_periph_1 || ORIG_REF_NAME==sys_bd_design_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/sys_bd_design/ip/sys_bd_design_DVI_Transmitter_0_0/sys_bd_design_DVI_Transmitter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_design_DVI_Transmitter_0_0 || ORIG_REF_NAME==sys_bd_design_DVI_Transmitter_0_0} -quiet] -quiet

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/sys_bd_design_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_design_smartconnect_0_0 || ORIG_REF_NAME==sys_bd_design_smartconnect_0_0} -quiet] -quiet

# Block Designs: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/bd_267f.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_0/bd_267f_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_1/bd_267f_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_2/bd_267f_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_3/bd_267f_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_4/bd_267f_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_5/bd_267f_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_6/bd_267f_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_7/bd_267f_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_8/bd_267f_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_9/bd_267f_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_10/bd_267f_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_11/bd_267f_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_12/bd_267f_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_13/bd_267f_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_14/bd_267f_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_15/bd_267f_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_16/bd_267f_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_17/bd_267f_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_18/bd_267f_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_19/bd_267f_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_20/bd_267f_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_21/bd_267f_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_22/bd_267f_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_23/bd_267f_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_24/bd_267f_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_25/bd_267f_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_26/bd_267f_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_27/bd_267f_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_28/bd_267f_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_29/bd_267f_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_30/bd_267f_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_31/bd_267f_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_32/bd_267f_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_33/bd_267f_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_34/bd_267f_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_35/bd_267f_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/sys_bd_design/ip/sys_bd_design_auto_pc_0/sys_bd_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_bd_design_auto_pc_0 || ORIG_REF_NAME==sys_bd_design_auto_pc_0} -quiet] -quiet

# XDC: bd/sys_bd_design/ip/sys_bd_design_processing_system7_0_0/sys_bd_design_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_bd_design_processing_system7_0_0 || ORIG_REF_NAME==sys_bd_design_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/sys_bd_design/ip/sys_bd_design_rst_ps7_0_50M_0/sys_bd_design_rst_ps7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_bd_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==sys_bd_design_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/sys_bd_design/ip/sys_bd_design_rst_ps7_0_50M_0/sys_bd_design_rst_ps7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_bd_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==sys_bd_design_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/sys_bd_design/ip/sys_bd_design_rst_ps7_0_50M_0/sys_bd_design_rst_ps7_0_50M_0_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_axi_vdma_0_1/sys_bd_design_axi_vdma_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_bd_design_axi_vdma_0_1 || ORIG_REF_NAME==sys_bd_design_axi_vdma_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/sys_bd_design/ip/sys_bd_design_axi_vdma_0_1/sys_bd_design_axi_vdma_0_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_bd_design_axi_vdma_0_1 || ORIG_REF_NAME==sys_bd_design_axi_vdma_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/sys_bd_design/ip/sys_bd_design_axi_vdma_0_1/sys_bd_design_axi_vdma_0_1_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_v_tc_0_1/sys_bd_design_v_tc_0_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_bd_design_v_tc_0_1 || ORIG_REF_NAME==sys_bd_design_v_tc_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/sys_bd_design/ip/sys_bd_design_v_tc_0_1/sys_bd_design_v_tc_0_1_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_v_axi4s_vid_out_0_1/sys_bd_design_v_axi4s_vid_out_0_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_bd_design_v_axi4s_vid_out_0_1 || ORIG_REF_NAME==sys_bd_design_v_axi4s_vid_out_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/sys_bd_design/ip/sys_bd_design_v_axi4s_vid_out_0_1/sys_bd_design_v_axi4s_vid_out_0_1_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_xbar_2/sys_bd_design_xbar_2_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_1/bd_267f_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_1/bd_267f_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_2/bd_267f_arsw_0_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_3/bd_267f_rsw_0_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_4/bd_267f_awsw_0_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_5/bd_267f_wsw_0_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_6/bd_267f_bsw_0_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_10/bd_267f_s00a2s_0_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_11/bd_267f_sarn_0_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_12/bd_267f_srn_0_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_13/bd_267f_sawn_0_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_14/bd_267f_swn_0_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_15/bd_267f_sbn_0_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_19/bd_267f_s01a2s_0_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_20/bd_267f_sarn_1_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_21/bd_267f_srn_1_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_22/bd_267f_m00s2a_0_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_23/bd_267f_m00arn_0_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_24/bd_267f_m00rn_0_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_25/bd_267f_m00awn_0_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_26/bd_267f_m00wn_0_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_27/bd_267f_m00bn_0_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_29/bd_267f_m01s2a_0_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_30/bd_267f_m01arn_0_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_31/bd_267f_m01rn_0_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_32/bd_267f_m01awn_0_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_33/bd_267f_m01wn_0_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_34/bd_267f_m01bn_0_ooc.xdc

# XDC: bd/sys_bd_design/ip/sys_bd_design_auto_pc_0/sys_bd_design_auto_pc_0_ooc.xdc

# XDC: bd/sys_bd_design/sys_bd_design_ooc.xdc
