# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.cache/wt [current_project]
set_property parent.project_path C:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/ip_repo [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/imports/pl/interpolation/average_adjust_16point.v
  C:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/imports/pl/interpolation/edge_16_generate.v
  C:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/imports/pl/interpolation/gauss_filter.v
  C:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/imports/pl/interpolation/gauss_filter_dot_36_4k.v
  C:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/imports/pl/interpolation/interpolate_16point.v
  C:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/imports/pl/interpolation/single_color_top.v
  C:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/imports/pl/interpolation/top.v
  C:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/imports/pl/key_debounce.v
  C:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/hdl/sys_bd_design_wrapper.v
}
add_files C:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/sys_bd_design.bd
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_processing_system7_0_0/sys_bd_design_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_rst_ps7_0_50M_0/sys_bd_design_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_rst_ps7_0_50M_0/sys_bd_design_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_rst_ps7_0_50M_0/sys_bd_design_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_axi_vdma_0_1/sys_bd_design_axi_vdma_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_axi_vdma_0_1/sys_bd_design_axi_vdma_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_axi_vdma_0_1/sys_bd_design_axi_vdma_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_v_tc_0_1/sys_bd_design_v_tc_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_v_tc_0_1/sys_bd_design_v_tc_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_v_axi4s_vid_out_0_1/sys_bd_design_v_axi4s_vid_out_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_v_axi4s_vid_out_0_1/sys_bd_design_v_axi4s_vid_out_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_xbar_2/sys_bd_design_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_1/bd_267f_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_1/bd_267f_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_2/bd_267f_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_3/bd_267f_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_4/bd_267f_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_5/bd_267f_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_6/bd_267f_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_10/bd_267f_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_11/bd_267f_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_12/bd_267f_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_13/bd_267f_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_14/bd_267f_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_15/bd_267f_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_19/bd_267f_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_20/bd_267f_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_21/bd_267f_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_22/bd_267f_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_23/bd_267f_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_24/bd_267f_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_25/bd_267f_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_26/bd_267f_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_27/bd_267f_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_29/bd_267f_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_30/bd_267f_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_31/bd_267f_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_32/bd_267f_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_33/bd_267f_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_smartconnect_0_0/bd_0/ip/ip_34/bd_267f_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/ip/sys_bd_design_auto_pc_0/sys_bd_design_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/sources_1/bd/sys_bd_design/sys_bd_design_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/constrs_1/new/pl_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/master/Desktop/final/CICC1837比赛资料/杯赛作品/vivado/fpga_hdmi/fpga_jjw1.srcs/constrs_1/new/pl_constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top sys_bd_design_wrapper -part xc7z020clg400-2 -directive AreaOptimized_medium -control_set_opt_threshold 1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef sys_bd_design_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file sys_bd_design_wrapper_utilization_synth.rpt -pb sys_bd_design_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
